env:
  browser: true
  es2021: true
  jest: true
extends:
  - react-app
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - standard-with-typescript
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
  - prettier
rules:
  react/react-in-jsx-scope: off
  camelcase: error
  spaced-comment: error
  quotes: [error, single]
  no-duplicate-imports: error
  no-console: 0
  no-empty: 0
  no-irregular-whitespace: 0
settings:
  react:
    version: detect
  import/resolver:
      "typescript": {}